// Schedule registry for the NEXVELON quote PDF document.
// A quote has an ordered list of QuoteScheduleInstance values; each is one
// page (or page section) in the rendered PDF. Five kinds exist:
//   - cover        Page 1: letterhead, addressing, scope-of-works paragraph
//   - particulars  Bill of materials, auto-derived from quote.sections
//   - agreement    Terms & Conditions, auto-derived from quote.terms
//   - acceptance   Totals + signature blocks + legal footer, auto-derived
//   - custom       User-typed body (plain text in v1; rich text in Chunk F)
//
// New quotes ship with cover + particulars + agreement + acceptance by
// default; admin can add/remove/reorder/rename schedules per-quote, and
// add as many custom schedules as needed.

import { newId } from "@/lib/quote-helpers";

export type QuoteScheduleKind =
  | "cover"
  | "particulars"
  | "drawings"
  | "agreement"
  | "acceptance"
  | "custom"
  | "assurance"
  | "dispatch";

export interface AssuranceCard {
  id: string;
  tier: string;        // free text, e.g. "GOLD TIER", "PLATINUM TIER"
  ornament: string;    // single character, e.g. "⚜", "✦", "❦", "◆"
  title: string;       // e.g. "Hardware Warranty"
  description: string; // e.g. "36 months · parts & labour · OEM-backed"
}

interface BaseScheduleInstance {
  id: string;
  kind: QuoteScheduleKind;
  title: string;       // editable per-quote
  subtitle: string;    // editable per-quote
  included: boolean;   // temporary disable without removing
}

export interface CoverScheduleInstance extends BaseScheduleInstance {
  kind: "cover";
  scopeOfWorks: string;
}

export interface ParticularsScheduleInstance extends BaseScheduleInstance {
  kind: "particulars";
}

export interface DrawingsScheduleInstance extends BaseScheduleInstance {
  kind: "drawings";
  scale?: string;      // optional — defaults to "N.T.S." (Not to Scale) when rendering
  notes?: string;      // optional — defaults undefined; future polish chunk may surface a UI for this
  // Phase 5b — uploaded PDF reference
  pdfPath?: string;        // Storage path: "{user_id}/{timestamp}-{filename}.pdf"
  pdfFilename?: string;    // Original filename for display
  pdfSize?: number;        // Bytes — for UI display
  pdfUploadedAt?: string;  // ISO timestamp of upload
}

export interface AgreementScheduleInstance extends BaseScheduleInstance {
  kind: "agreement";
}

export interface AcceptanceScheduleInstance extends BaseScheduleInstance {
  kind: "acceptance";
}

export interface CustomScheduleInstance extends BaseScheduleInstance {
  kind: "custom";
  body: string;        // plain text in v1; replaced with rich-text JSON in Chunk F
}

export interface AssuranceScheduleInstance extends BaseScheduleInstance {
  kind: "assurance";
  cards: AssuranceCard[];
}

// GF-2 — Guardian-only dispatch & false-alarm election. Captures the Client's
// police/fire/ambulance dispatch authorization and the accept-regional-fees vs
// decline-police election, plus editable regional-fee and private-response
// notes. Self-contained — no pricing, no totals.
export interface DispatchScheduleInstance extends BaseScheduleInstance {
  kind: "dispatch";
  election: "accept_regional" | "decline_police";
  authorizePolice: boolean;
  authorizeFire: boolean;
  authorizeAmbulance: boolean;
  regionalFeeNote?: string;
  privateResponseNote?: string;
}

export type QuoteScheduleInstance =
  | CoverScheduleInstance
  | ParticularsScheduleInstance
  | DrawingsScheduleInstance
  | AgreementScheduleInstance
  | AcceptanceScheduleInstance
  | CustomScheduleInstance
  | AssuranceScheduleInstance
  | DispatchScheduleInstance;

export interface QuoteScheduleDefinition {
  kind: QuoteScheduleKind;
  defaultTitle: string;
  defaultSubtitle: string;
  description: string;
  autoGenerated: boolean;
  allowMultiple: boolean;
}

export const QUOTE_SCHEDULE_DEFINITIONS: Record<QuoteScheduleKind, QuoteScheduleDefinition> = {
  cover: {
    kind: "cover",
    defaultTitle: "Quotation",
    defaultSubtitle: "A Proposal of Works",
    description: "Cover page with letterhead, client and site addressing, key dates, and scope-of-works paragraph.",
    autoGenerated: false,
    allowMultiple: false,
  },
  particulars: {
    kind: "particulars",
    defaultTitle: "Particulars",
    defaultSubtitle: "Bill of Materials",
    description: "Itemised bill of materials with section subtotals, HST, and grand total. Auto-derived from the quote's line items.",
    autoGenerated: true,
    allowMultiple: false,
  },
  drawings: {
    kind: "drawings",
    defaultTitle: "Drawings & Take-off",
    defaultSubtitle: "Drawings & Take-off",
    description: "Bounded drawing area for site drawings, with an auto-generated take-off summary of line items grouped by classification.",
    autoGenerated: false,
    allowMultiple: false,
  },
  agreement: {
    kind: "agreement",
    defaultTitle: "The Agreement",
    defaultSubtitle: "Terms & Conditions",
    description: "Numbered terms and conditions clauses. Auto-derived from the quote's terms field.",
    autoGenerated: true,
    allowMultiple: false,
  },
  acceptance: {
    kind: "acceptance",
    defaultTitle: "For Acceptance",
    defaultSubtitle: "",
    description: "Total amount, signature blocks for client and Nexvelon, and HST and legal footer. Auto-derived from the quote's totals.",
    autoGenerated: true,
    allowMultiple: false,
  },
  custom: {
    kind: "custom",
    defaultTitle: "New Schedule",
    defaultSubtitle: "Custom Section",
    description: "Free-form schedule with admin-written body content. Use for narratives, addenda, project context, or anything else.",
    autoGenerated: false,
    allowMultiple: true,
  },
  assurance: {
    kind: "assurance",
    defaultTitle: "The Assurance",
    defaultSubtitle: "Warranty & Service",
    description: "Warranty and service tier cards. Ships with four default cards; admin can add, remove, reorder, and edit each card per quote.",
    autoGenerated: false,
    allowMultiple: false,
  },
  dispatch: {
    kind: "dispatch",
    defaultTitle: "Dispatch & False-Alarm Election",
    defaultSubtitle: "Authority dispatch and regional false-alarm fees",
    description: "Client's police/fire/ambulance dispatch authorization and acknowledgment of regional false-alarm fees.",
    autoGenerated: false,
    allowMultiple: false,
  },
};

export const DEFAULT_QUOTE_SCHEDULE_KINDS: QuoteScheduleKind[] = [
  "cover",
  "particulars",
  "assurance",
  "agreement",
  "acceptance",
];

export function createAssuranceSchedule(): AssuranceScheduleInstance {
  return {
    id: newId("sch"),
    kind: "assurance",
    title: QUOTE_SCHEDULE_DEFINITIONS.assurance.defaultTitle,
    subtitle: QUOTE_SCHEDULE_DEFINITIONS.assurance.defaultSubtitle,
    included: true,
    cards: [
      { id: newId("card"), tier: "GOLD TIER",     ornament: "⚜", title: "Hardware Warranty",    description: "36 months · parts & labour · OEM-backed" },
      { id: newId("card"), tier: "GOLD TIER",     ornament: "⚜", title: "Workmanship Warranty", description: "24 months · installation & commissioning" },
      { id: newId("card"), tier: "PLATINUM TIER", ornament: "✦", title: "Service Tier",         description: "4-hour response · 24 / 7 · dedicated technician" },
      { id: newId("card"), tier: "PLATINUM TIER", ornament: "✦", title: "System Audit",         description: "Quarterly audit · annual firmware update" },
    ],
  };
}

export function createDispatchSchedule(): DispatchScheduleInstance {
  const def = QUOTE_SCHEDULE_DEFINITIONS.dispatch;
  return {
    id: newId("sch"),
    kind: "dispatch",
    title: def.defaultTitle,
    subtitle: def.defaultSubtitle,
    included: true,
    election: "accept_regional",
    authorizePolice: true,
    authorizeFire: true,
    authorizeAmbulance: true,
    regionalFeeNote:
      "Police, fire, and emergency services in each municipality or region set their own false-alarm, cancelled-alarm, and registration fees, which vary by region and change over time. The Client is responsible for all such fees and fines. In some regions, authorities will not respond unless the applicable fees have been acknowledged or accepted.",
    privateResponseNote:
      "If police dispatch is declined, Nexvelon will instead contact the Client's keyholders and/or a private security guard service; response times may be materially longer than typical police response, and the Client is responsible for any private guard charges.",
  };
}

export function createDefaultSchedules(): QuoteScheduleInstance[] {
  return [
    {
      id: newId("sch"),
      kind: "cover",
      title: QUOTE_SCHEDULE_DEFINITIONS.cover.defaultTitle,
      subtitle: QUOTE_SCHEDULE_DEFINITIONS.cover.defaultSubtitle,
      included: true,
      scopeOfWorks: "",
    },
    {
      id: newId("sch"),
      kind: "particulars",
      title: QUOTE_SCHEDULE_DEFINITIONS.particulars.defaultTitle,
      subtitle: QUOTE_SCHEDULE_DEFINITIONS.particulars.defaultSubtitle,
      included: true,
    },
    createAssuranceSchedule(),
    {
      id: newId("sch"),
      kind: "agreement",
      title: QUOTE_SCHEDULE_DEFINITIONS.agreement.defaultTitle,
      subtitle: QUOTE_SCHEDULE_DEFINITIONS.agreement.defaultSubtitle,
      included: true,
    },
    {
      id: newId("sch"),
      kind: "acceptance",
      title: QUOTE_SCHEDULE_DEFINITIONS.acceptance.defaultTitle,
      subtitle: QUOTE_SCHEDULE_DEFINITIONS.acceptance.defaultSubtitle,
      included: true,
    },
  ];
}

export function createDrawingsSchedule(): DrawingsScheduleInstance {
  const def = QUOTE_SCHEDULE_DEFINITIONS.drawings;
  return {
    id: newId("sch"),
    kind: "drawings",
    title: def.defaultTitle,
    subtitle: def.defaultSubtitle,
    included: true,
    scale: undefined,
    notes: undefined,
  };
}

export function createCustomSchedule(title?: string): CustomScheduleInstance {
  return {
    id: newId("sch"),
    kind: "custom",
    title: title ?? QUOTE_SCHEDULE_DEFINITIONS.custom.defaultTitle,
    subtitle: QUOTE_SCHEDULE_DEFINITIONS.custom.defaultSubtitle,
    included: true,
    body: "",
  };
}
