// Schedule registry for the NEXVELON quote PDF document.
// A quote has an ordered list of QuoteScheduleInstance values; each is one
// page (or page section) in the rendered PDF. Five kinds exist:
//   - cover        Page 1: letterhead, addressing, scope-of-works paragraph
//   - particulars  Bill of materials, auto-derived from quote.sections
//   - agreement    Terms & Conditions, auto-derived from quote.terms
//   - acceptance   Totals + signature blocks + legal footer, auto-derived
//   - custom       User-typed body (plain text in v1; rich text in Chunk F)
//
// New quotes ship with cover + particulars + agreement + acceptance by
// default; admin can add/remove/reorder/rename schedules per-quote, and
// add as many custom schedules as needed.

import { newId } from "@/lib/quote-helpers";

export type QuoteScheduleKind =
  | "cover"
  | "particulars"
  | "agreement"
  | "acceptance"
  | "custom"
  | "assurance";

export interface AssuranceCard {
  id: string;
  tier: string;        // free text, e.g. "GOLD TIER", "PLATINUM TIER"
  ornament: string;    // single character, e.g. "⚜", "✦", "❦", "◆"
  title: string;       // e.g. "Hardware Warranty"
  description: string; // e.g. "36 months · parts & labour · OEM-backed"
}

export interface ExclusionItem {
  id: string;
  text: string;
}

interface BaseScheduleInstance {
  id: string;
  kind: QuoteScheduleKind;
  title: string;       // editable per-quote
  subtitle: string;    // editable per-quote
  included: boolean;   // temporary disable without removing
}

export interface CoverScheduleInstance extends BaseScheduleInstance {
  kind: "cover";
  scopeOfWorks: string;
}

export interface ParticularsScheduleInstance extends BaseScheduleInstance {
  kind: "particulars";
}

export interface AgreementScheduleInstance extends BaseScheduleInstance {
  kind: "agreement";
  exclusions?: ExclusionItem[];
}

export interface AcceptanceScheduleInstance extends BaseScheduleInstance {
  kind: "acceptance";
}

export interface CustomScheduleInstance extends BaseScheduleInstance {
  kind: "custom";
  body: string;        // plain text in v1; replaced with rich-text JSON in Chunk F
}

export interface AssuranceScheduleInstance extends BaseScheduleInstance {
  kind: "assurance";
  cards: AssuranceCard[];
}

export type QuoteScheduleInstance =
  | CoverScheduleInstance
  | ParticularsScheduleInstance
  | AgreementScheduleInstance
  | AcceptanceScheduleInstance
  | CustomScheduleInstance
  | AssuranceScheduleInstance;

export interface QuoteScheduleDefinition {
  kind: QuoteScheduleKind;
  defaultTitle: string;
  defaultSubtitle: string;
  description: string;
  autoGenerated: boolean;
  allowMultiple: boolean;
}

export const QUOTE_SCHEDULE_DEFINITIONS: Record<QuoteScheduleKind, QuoteScheduleDefinition> = {
  cover: {
    kind: "cover",
    defaultTitle: "Quotation",
    defaultSubtitle: "A Proposal of Works",
    description: "Cover page with letterhead, client and site addressing, key dates, and scope-of-works paragraph.",
    autoGenerated: false,
    allowMultiple: false,
  },
  particulars: {
    kind: "particulars",
    defaultTitle: "Particulars",
    defaultSubtitle: "Bill of Materials",
    description: "Itemised bill of materials with section subtotals, HST, and grand total. Auto-derived from the quote's line items.",
    autoGenerated: true,
    allowMultiple: false,
  },
  agreement: {
    kind: "agreement",
    defaultTitle: "The Agreement",
    defaultSubtitle: "Terms & Conditions",
    description: "Numbered terms and conditions clauses. Auto-derived from the quote's terms field.",
    autoGenerated: true,
    allowMultiple: false,
  },
  acceptance: {
    kind: "acceptance",
    defaultTitle: "For Acceptance",
    defaultSubtitle: "",
    description: "Total amount, signature blocks for client and Nexvelon, and HST and legal footer. Auto-derived from the quote's totals.",
    autoGenerated: true,
    allowMultiple: false,
  },
  custom: {
    kind: "custom",
    defaultTitle: "New Schedule",
    defaultSubtitle: "Custom Section",
    description: "Free-form schedule with admin-written body content. Use for narratives, addenda, project context, or anything else.",
    autoGenerated: false,
    allowMultiple: true,
  },
  assurance: {
    kind: "assurance",
    defaultTitle: "The Assurance",
    defaultSubtitle: "Warranty & Service",
    description: "Warranty and service tier cards. Ships with four default cards; admin can add, remove, reorder, and edit each card per quote.",
    autoGenerated: false,
    allowMultiple: false,
  },
};

export const DEFAULT_QUOTE_SCHEDULE_KINDS: QuoteScheduleKind[] = [
  "cover",
  "particulars",
  "assurance",
  "agreement",
  "acceptance",
];

export function createDefaultExclusions(): ExclusionItem[] {
  return [
    { id: newId("exc"), text: "Conduit, cable trays, and core drilling beyond 4 penetrations" },
    { id: newId("exc"), text: "120V power, breaker panel work, and any electrical permits" },
    { id: newId("exc"), text: "Network switches, PoE injectors, and structured cabling backbone" },
    { id: newId("exc"), text: "Patching, painting, or making good after wall openings" },
    { id: newId("exc"), text: "After-hours or weekend labour unless specified above" },
    { id: newId("exc"), text: "Permits, inspections, and authority-having-jurisdiction fees" },
  ];
}

export function createAssuranceSchedule(): AssuranceScheduleInstance {
  return {
    id: newId("sch"),
    kind: "assurance",
    title: QUOTE_SCHEDULE_DEFINITIONS.assurance.defaultTitle,
    subtitle: QUOTE_SCHEDULE_DEFINITIONS.assurance.defaultSubtitle,
    included: true,
    cards: [
      { id: newId("card"), tier: "GOLD TIER",     ornament: "⚜", title: "Hardware Warranty",    description: "36 months · parts & labour · OEM-backed" },
      { id: newId("card"), tier: "GOLD TIER",     ornament: "⚜", title: "Workmanship Warranty", description: "24 months · installation & commissioning" },
      { id: newId("card"), tier: "PLATINUM TIER", ornament: "✦", title: "Service Tier",         description: "4-hour response · 24 / 7 · dedicated technician" },
      { id: newId("card"), tier: "PLATINUM TIER", ornament: "✦", title: "System Audit",         description: "Quarterly audit · annual firmware update" },
    ],
  };
}

export function createDefaultSchedules(): QuoteScheduleInstance[] {
  return [
    {
      id: newId("sch"),
      kind: "cover",
      title: QUOTE_SCHEDULE_DEFINITIONS.cover.defaultTitle,
      subtitle: QUOTE_SCHEDULE_DEFINITIONS.cover.defaultSubtitle,
      included: true,
      scopeOfWorks: "",
    },
    {
      id: newId("sch"),
      kind: "particulars",
      title: QUOTE_SCHEDULE_DEFINITIONS.particulars.defaultTitle,
      subtitle: QUOTE_SCHEDULE_DEFINITIONS.particulars.defaultSubtitle,
      included: true,
    },
    createAssuranceSchedule(),
    {
      id: newId("sch"),
      kind: "agreement",
      title: QUOTE_SCHEDULE_DEFINITIONS.agreement.defaultTitle,
      subtitle: QUOTE_SCHEDULE_DEFINITIONS.agreement.defaultSubtitle,
      included: true,
      exclusions: createDefaultExclusions(),
    },
    {
      id: newId("sch"),
      kind: "acceptance",
      title: QUOTE_SCHEDULE_DEFINITIONS.acceptance.defaultTitle,
      subtitle: QUOTE_SCHEDULE_DEFINITIONS.acceptance.defaultSubtitle,
      included: true,
    },
  ];
}

export function createCustomSchedule(title?: string): CustomScheduleInstance {
  return {
    id: newId("sch"),
    kind: "custom",
    title: title ?? QUOTE_SCHEDULE_DEFINITIONS.custom.defaultTitle,
    subtitle: QUOTE_SCHEDULE_DEFINITIONS.custom.defaultSubtitle,
    included: true,
    body: "",
  };
}
