// UIDG-2 — emits the [data-theme] CSS blocks from the THEMES single source
// (lib/theme.ts). Pure string builder: no fs, no side effects, so it is unit
// testable and reused by scripts/generate-theme-css.ts (which writes the file).
//
// The derivation block in app/globals.css (:root mapping --brand-* → shadcn
// tokens) and the .dark block are NOT emitted here — those stay hand-written.

import {
  DEFAULT_THEME,
  THEME_ORDER,
  resolveTheme,
  type ThemeTokens,
} from "./theme";

export const GENERATED_HEADER =
  "/* AUTO-GENERATED by scripts/generate-theme-css.ts — DO NOT EDIT.\n" +
  "   Source of truth: lib/theme.ts (THEMES). Regenerate: `npm run gen:theme`. */\n";

/** The ordered `--brand-*` / `--brand-font-*` declarations for one theme's tokens. */
function declarations(t: ThemeTokens): string {
  const lines: [string, string][] = [
    ["--brand-primary", t.primary],
    ["--brand-accent", t.accent],
    ["--brand-accent-soft", t.accentSoft],
    ["--brand-bg", t.bg],
    ["--brand-text", t.text],
    ["--brand-card", t.card],
    ["--brand-border", t.border],
    ["--brand-muted", t.muted],
    ["--brand-sidebar-accent", t.sidebarAccent],
    ["--brand-sidebar-border", t.sidebarBorder],
    ["--brand-chart-tertiary", t.chartTertiary],
    ["--brand-chart-quaternary", t.chartQuaternary],
    ["--brand-status-green", t.statusGreen],
    ["--brand-status-red", t.statusRed],
    ["--brand-font-sans", t.fonts.sans],
    ["--brand-font-serif", t.fonts.serif],
    ["--brand-font-mono", t.fonts.mono],
  ];
  return lines.map(([k, v]) => `  ${k}: ${v};`).join("\n");
}

/** Light selector for a preset. The default theme also claims bare `:root` so the
 *  app renders correctly (default theme) even before the bootstrap script or with
 *  JS disabled. */
function lightSelector(key: string): string {
  return key === DEFAULT_THEME
    ? `:root,\n:root[data-theme="${key}"]`
    : `:root[data-theme="${key}"]`;
}

/** UIDG-4B — dark selector: scoped under the `.dark` class on <html> (the same
 *  signal shadcn's `dark:` utilities use), one specificity step above the light
 *  block so it wins when dark is active. */
function darkSelector(key: string): string {
  return key === DEFAULT_THEME
    ? `:root.dark,\n:root.dark[data-theme="${key}"]`
    : `:root.dark[data-theme="${key}"]`;
}

/** The full generated CSS partial (imported by app/globals.css): a light AND a
 *  dark `--brand-*` block for every preset. */
export function themePresetsCss(): string {
  const blocks: string[] = [];
  for (const key of THEME_ORDER) {
    blocks.push(`${lightSelector(key)} {\n${declarations(resolveTheme(key, "light"))}\n}`);
    blocks.push(`${darkSelector(key)} {\n${declarations(resolveTheme(key, "dark"))}\n}`);
  }
  return `${GENERATED_HEADER}\n${blocks.join("\n\n")}\n`;
}

/**
 * UIDG-4/4B — the light + dark `[data-theme]` blocks for an arbitrary theme value
 * + tokens. Built-in presets are pre-generated in the committed partial above;
 * custom themes are per-user DB rows that can't be, so the layout injects these
 * server-side (inline <style>) for the active custom theme — first paint stays
 * correct with no flash and no JS in either mode — and the client reuses them for
 * live preview. `dark` is the derived (or edited) dark token set.
 */
export function renderThemeBlocks(
  dataThemeValue: string,
  light: ThemeTokens,
  dark: ThemeTokens
): string {
  return (
    `:root[data-theme="${dataThemeValue}"] {\n${declarations(light)}\n}\n\n` +
    `:root.dark[data-theme="${dataThemeValue}"] {\n${declarations(dark)}\n}`
  );
}
